// <auto-generated />
using System;
using BankingWebAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingAPI.Migrations.TransactionsHistoryDB
{
    [DbContext(typeof(TransactionsHistoryDBContext))]
    [Migration("20221018132435_IniyialCreate")]
    partial class IniyialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BankingWebAPI.Models.TransactionsHistory", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transactionId"), 1L, 1);

                    b.Property<double>("amountDebit")
                        .HasColumnType("float");

                    b.Property<double>("fromAccountBalance")
                        .HasColumnType("float")
                        .HasColumnName("fromAccountBalance");

                    b.Property<int>("fromAccountNumber")
                        .HasColumnType("int")
                        .HasColumnName("fromAccountNumber");

                    b.Property<double>("toAccountBalance")
                        .HasColumnType("float")
                        .HasColumnName("toAccountBalance");

                    b.Property<int>("toAccountNumber")
                        .HasColumnType("int")
                        .HasColumnName("toAccountNumber");

                    b.Property<DateTime>("transactionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("transactionTime");

                    b.HasKey("transactionId");

                    b.ToTable("TransactionsHistory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
